### ISSUE TITLE
convergence criterium positive loss change

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/batchglm#48]
I noticed that Newton-type solver converge relatively good in some cases but than bounce off to extremely bad objective values within a single step. This might be because they reach plateaus around the MLE where the quadratic approximation is bad. One easy way to mitigate this, which worked for me in the past, was to evaluate convergence in these cases by step (no batching!):
if loss change is negative, update parameters and continue
else do not update parameters and return
What do you think @Hoeze ? 
I think the way this is coded now it we would have to perform the update step, check for this criterium
and revert the parameter update and return if the objective is not improved.

**Comment by Hoeze** [comment]
Yes, I think this should work since the NR should lower the loss monotonically.
So, if the loss raises in one step, there has to be something wrong.

Since we are calculating the loss in each step anyways, we can just keep the feature probabilities of the last step in a tf.Variable, so performance cost of this check can be kept very low.

**Comment by davidsebfischer** [comment]
Done in https://github.com/theislab/batchglm/pull/55, referenced as feature-wise termination.
