### ISSUE TITLE
Remove log(exp(mu)) and log(exp(r)) where possible

### ISSUE THREAD

**Issue by Hoeze** [theislab/batchglm#53]
Current implementation of negative binomial distribution uses log_mu and log_r.
Directly providing log_mu and log_r saves computation time and improves numeric stability.

**Comment by davidsebfischer** [comment]
I will hardcode the maths of the log-likelihood as a tensorflow graph in a separate function and link that function to likelihood evaluations in the model in BasicModelGraph, that should replace all calls to the previous implementation which contains this redundancy because of its interface to BasicModelGraph. I will do a quick benchmark how this affects run time.

**Comment by Hoeze** [comment]
You can look into the rsa_dev branch, there is already such an TF-NB implementation

**Comment by Hoeze** [comment]
Although without the improvement mentioned here and not very clean...

**Comment by davidsebfischer** [comment]
Done in https://github.com/theislab/batchglm/pull/55/commits/88def86c64c0f83a6a3b10a44fc50593194b5802.
