### ISSUE TITLE
[TF2] FIM_a and FIM_b cannot be concatenated when using intercept_scale: results in exception.

### ISSUE THREAD

**Issue by picciama** [theislab/batchglm#98]
Problem Analysis:
When using intercept_scale, the dispersion model is fitted on the intercept only, therefore producing an output matrix with the shape [1,c,c], where c is the number of coefficients (#conditions + #batches -1 for the intercept). The mean model has dimensions [c,c,c] however. 
Currently, we concatenate both `FIM_a` and `FIM_b` after fitting to provide a single property in the model container.
https://github.com/theislab/batchglm/blob/e4a5594b821ce2163c04fe59b0b7fd46354d2b5b/batchglm/train/tf2/base_glm/estimator.py#L254-L255

How is it solved in tf1?
The property `self.model.fisher_inv` defined in `finalize`:
https://github.com/theislab/batchglm/blob/23484819f0cdb4778c88ad9e68aebbdba0b5c814/batchglm/train/tf1/base_glm_all/estimator.py#L331

is simply storing hessian instead whch is known (TODO):
https://github.com/theislab/batchglm/blob/23484819f0cdb4778c88ad9e68aebbdba0b5c814/batchglm/train/tf1/base_glm_all/estimator_graph.py#L531

Proposed solution:
Store either two properties fim_a and fim_b or a tuple. But never concatenate the two?

**Comment by davidsebfischer** [comment]
Can you also save the negative hessian here? this is the safest way of doing this right now, most exact and only a bit slower. This solves all of your problems as well.

**Comment by davidsebfischer** [comment]
If want to change this later, we ll have to deal with that in all 3 backends anyway

**Comment by picciama** [comment]
> Can you also save the negative hessian here? this is the safest way of doing this right now, most exact and only a bit slower. This solves all of your problems as well.

So fitting procedure with FIM but then reporting the hessian?
Please keep in mind, that hessian autograd is not yet functional in tf2. It is currently solved by logging a warning that the fallback analytic differentiation is used instead. However, it does not make sense to report Hessian but use FIM.

**Comment by davidsebfischer** [comment]
Yes, here you would use the analytic form of the hessian. We use FIM for optimisation because FIM is faster to evaluate, keep in mind it is just "used as an approximates of the hessian" during optimisation. At convergence, the FIM has converged to the hessian as the expectation of the difference {between the model mean the data mean} over the data distribution approach zero. So it is completely fine to use the hessian here. Here FIM is connected to MLE covariance which is why the output parameter is called fim, but we can evaluate it as the hessian.

**Comment by davidsebfischer** [comment]
In terms of implementation, this solves the problem that there is no analytic form of the FIM for the scale model of NB for example.

**Comment by picciama** [comment]
I need to change a few things for this, which I will push on the tf2 branch once finished.

**Comment by picciama** [comment]
Ok, I analysed the issues and the following problems arise:
1. the concatenation problem also affects jacobians. 
2. If you want to compute hessians although using IRLS, the final model call will be executed with the next smaller input, when using `featurewise`, which is essentially a zero dimensional input because every individual feature parameter has already converged at this point. 

So there are two problems, featurewise and the different dimensions when using intercept_scale, we cannot circumvent this problem (i.e. jacobians are defined for nb).

We need to compute jacobians, hessians and fims without `featurewise` in the final run.
The `intercept_scale` problem can only be solved using two variables or a tuple, but we cannot concatenate them. 
But I am wondering why we would do that anyways, since they should be extremely close to zero once every parameter converges. What information do we get out of them?

https://github.com/theislab/batchglm/blob/486d1ba7b294eada729cb42abd74392b7d8019d1/batchglm/train/tf2/base_glm/estimator.py#L286-L290
I removed it for now as you can see, since there is no obvious and quick fix.

**Comment by davidsebfischer** [comment]
> the concatenation problem also affects jacobians.

I do not see an issue, the problem you mentioned for the FIM was about the two (length of coeficient set) dimensions not aligning. The jacobians are shape (theta, features), you can just concatenate location and scale model jacobians to (theta_loc + theta_scale, features).

> We need to compute jacobians, hessians and fims without featurewise in the final run.

Definitely, we need this hessian (or this FIM, but we dont use that) all features. I do not see why this is an issue though? This is just a forward pass to the hessian for all features. You did this before, otherwise you wouldnt be able to use this code for differential expression analysis.

**Comment by picciama** [comment]
I resolved the issues arising from featurewise calculation. It runs a final evaluation over the entire featurespace, looping over all batches and adding up the results now.
